namespace OnHive.Core.Library.Constants
{
    public static class AddressConstants
    {
        public static string GetStateName(string code)
        {
            return code switch
            {
                "AC" => "Acre",
                "AL" => "Alagoas",
                "AP" => "Amapá",
                "AM" => "Amazonas",
                "BA" => "Bahia",
                "CE" => "Ceará",
                "DF" => "Distrito Federal",
                "ES" => "Espírito Santo",
                "GO" => "Goiás",
                "MA" => "Maranhão",
                "MT" => "Mato Grosso",
                "MS" => "Mato Grosso do Sul",
                "MG" => "Minas Gerais",
                "PA" => "Pará",
                "PB" => "Paraíba",
                "PR" => "Paraná",
                "PE" => "Pernambuco",
                "PI" => "Piauí",
                "RJ" => "Rio de Janeiro",
                "RN" => "Rio Grande do Norte",
                "RS" => "Rio Grande do Sul",
                "RO" => "Rondônia",
                "RR" => "Roraima",
                "SC" => "Santa Catarina",
                "SP" => "São Paulo",
                "SE" => "Sergipe",
                "TO" => "Tocantins",
                _ => "Exterior"
            };
        }

        public static string GetCountryName(string code)
        {
            return code switch
            {
                "AF" => "Afeganistão",
                "ZA" => "África do Sul",
                "AL" => "Albânia",
                "DZ" => "Argélia",
                "DE" => "Alemanha",
                "AD" => "Andorra",
                "AO" => "Angola",
                "AI" => "Anguilla",
                "AQ" => "Antártida",
                "AG" => "Antígua e Barbuda",
                "SA" => "Arábia Saudita",
                "AR" => "Argentina",
                "AM" => "Armênia",
                "AW" => "Aruba",
                "AU" => "Austrália",
                "AT" => "Áustria",
                "AZ" => "Azerbaijão",
                "BS" => "Bahamas",
                "BD" => "Bangladesh",
                "BB" => "Barbados",
                "BH" => "Barein",
                "BY" => "Belarus",
                "BE" => "Bélgica",
                "BZ" => "Belize",
                "BJ" => "Benin",
                "BM" => "Bermudas",
                "BO" => "Bolívia",
                "BA" => "Bósnia e Herzegovina",
                "BW" => "Botsuana",
                "BR" => "Brasil",
                "BN" => "Brunei",
                "BG" => "Bulgária",
                "BF" => "Burkina Faso",
                "BI" => "Burundi",
                "BT" => "Butão",
                "CV" => "Cabo Verde",
                "CM" => "Camarões",
                "KH" => "Camboja",
                "CA" => "Canadá",
                "QA" => "Catar",
                "KZ" => "Cazaquistão",
                "TD" => "Chade",
                "CL" => "Chile",
                "CN" => "China",
                "CY" => "Chipre",
                "SG" => "Cingapura",
                "CO" => "Colômbia",
                "KM" => "Comores",
                "CG" => "Congo",
                "KP" => "Coreia do Norte",
                "KR" => "Coreia do Sul",
                "CI" => "Costa do Marfim",
                "CR" => "Costa Rica",
                "HR" => "Croácia",
                "CU" => "Cuba",
                "CW" => "Curaçao",
                "DK" => "Dinamarca",
                "DJ" => "Djibuti",
                "DM" => "Dominica",
                "EG" => "Egito",
                "SV" => "El Salvador",
                "AE" => "Emirados Árabes Unidos",
                "EC" => "Equador",
                "ER" => "Eritreia",
                "SK" => "Eslováquia",
                "SI" => "Eslovênia",
                "ES" => "Espanha",
                "US" => "Estados Unidos da América",
                "EE" => "Estônia",
                "ET" => "Etiópia",
                "FJ" => "Fiji",
                "PH" => "Filipinas",
                "FI" => "Finlândia",
                "FR" => "França",
                "GA" => "Gabão",
                "GM" => "Gâmbia",
                "GH" => "Gana",
                "GE" => "Geórgia",
                "GI" => "Gibraltar",
                "GD" => "Granada",
                "GR" => "Grécia",
                "GL" => "Groenlândia",
                "GP" => "Guadalupe",
                "GU" => "Guam",
                "GT" => "Guatemala",
                "GG" => "Guernsey",
                "GY" => "Guiana",
                "GF" => "Guiana Francesa",
                "GN" => "Guiné",
                "GW" => "Guiné-Bissau",
                "GQ" => "Guiné Equatorial",
                "HT" => "Haiti",
                "HN" => "Honduras",
                "HK" => "Hong Kong",
                "HU" => "Hungria",
                "YE" => "Iêmen",
                "BV" => "Ilha Bouvet",
                "IM" => "Ilha de Man",
                "NF" => "Ilha Norfolk",
                "AX" => "Ilhas Åland",
                "KY" => "Ilhas Cayman",
                "CC" => "Ilhas Cocos",
                "CK" => "Ilhas Cook",
                "FO" => "Ilhas Faroe",
                "GS" => "Ilhas Geórgia do Sul e Sandwich do Sul",
                "HM" => "Ilhas Heard e McDonald",
                "FK" => "Ilhas Malvinas",
                "MP" => "Ilhas Marianas do Norte",
                "MH" => "Ilhas Marshall",
                "UM" => "Ilhas Menores Distantes dos Estados Unidos",
                "PN" => "Ilhas Pitcairn",
                "SB" => "Ilhas Salomão",
                "TC" => "Ilhas Turks e Caicos",
                "VG" => "Ilhas Virgens Britânicas",
                "VI" => "Ilhas Virgens dos EUA",
                "IN" => "Índia",
                "ID" => "Indonésia",
                "IR" => "Irã",
                "IQ" => "Iraque",
                "IE" => "Irland",
                _ => "Desconhecido"
            };
        }
    }
}