using Blazored.LocalStorage;
using OnHive.Admin;
using OnHive.Admin.Helpers;
using OnHive.Admin.Models;
using OnHive.Admin.Services;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
using MudBlazor.Services;
using Radzen;

var builder = WebAssemblyHostBuilder.CreateDefault(args);
builder.RootComponents.Add<App>("#app");
builder.RootComponents.Add<HeadOutlet>("head::after");
builder.Services.AddSingleton(sp => new HttpClient { BaseAddress = new Uri(builder.HostEnvironment.BaseAddress) });
var host = builder.HostEnvironment.BaseAddress;
if (host.EndsWith("/")) host = host.Substring(0, host.Length - 1);
builder.Services.AddSingleton(sp => new EnvironmentSettings { ApiHost = host });
builder.Services.AddRadzenComponents();
builder.Services.AddMudServices();
builder.Services.AddBlazoredLocalStorageAsSingleton();
builder.Services.AddSingleton<IClipboardHelper, ClipboardHelper>();
builder.Services.AddSingleton<ILoginService, LoginService>();
builder.Services.AddSingleton<ITenantsService, TenantsService>();
builder.Services.AddSingleton<IRolesService, RolesService>();
builder.Services.AddSingleton<IUsersService, UsersService>();
builder.Services.AddSingleton<ICoursesService, CoursesService>();
builder.Services.AddSingleton<IDisciplinesService, DisciplinesService>();
builder.Services.AddSingleton<ILessonsService, LessonsService>();
builder.Services.AddSingleton<IExamsService, ExamsService>();
builder.Services.AddSingleton<IProductsService, ProductsService>();
builder.Services.AddSingleton<IAutomationsService, AutomationsService>();
builder.Services.AddSingleton<IEventsService, EventsService>();
builder.Services.AddSingleton<IEventsConfigService, EventsConfigService>();
builder.Services.AddSingleton<IRedirectsService, RedirectsService>();
builder.Services.AddSingleton<IStudentsService, StudentsService>();
builder.Services.AddSingleton<IStorageService, StorageService>();
builder.Services.AddSingleton<IPostsService, PostsService>();
builder.Services.AddSingleton<IAdminService, AdminService>();
builder.Services.AddSingleton<IDictService, DictService>();
builder.Services.AddSingleton<IUserGroupsService, UserGroupsService>();
builder.Services.AddSingleton<IMessagesService, MessagesService>();
builder.Services.AddSingleton<IMessageChannelsService, MessageChannelsService>();
builder.Services.AddSingleton<IEmailTemplateService, EmailTemplateService>();
builder.Services.AddSingleton<ISearchService, SearchService>();
builder.Services.AddSingleton<IWebhookService, WebhookService>();
builder.Services.AddSingleton<IUserProfileService, UserProfileService>();
builder.Services.AddSingleton<IVideoService, VideoService>();
builder.Services.AddSingleton<ICertificatesService, CertificatesService>();
builder.Services.AddSingleton<IMauticIntegrationService, MauticIntegrationService>();
builder.Services.AddSingleton<IStudentReportsService, StudentReportsService>();

await builder.Build().RunAsync();